name: flutter_multi_table
description: A Flutter plugin for creating and managing dynamic, multi-column tables with customizable features such as dropdowns, validation, read-only cells, and more. Ideal for applications that require interactive table inputs and structured data handling.
version: 0.0.1
homepage: https://github.com/adampermana/flutter_multi_table.git
repository: https://github.com/adampermana/flutter_multi_table.git
issue_tracker: https://github.com/adampermana/flutter_multi_table/issues
topics: [table, tables, multi-table]
license: MIT

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.0 <6.0.0"